-- Schema file is automatically generated by dbmate
-- DO NOT EDIT THIS FILE MANUALLY

-- This file is used as a reference for the current database schema
-- It is updated automatically when migrations are applied
