apiVersion: 1

templates:
  - name: discord.title
    template: |
      [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }}

  - name: discord.message
    template: |
      {{ range .Alerts }}
      **Status:** {{ .Status | toUpper }}
      **Alert:** {{ .Labels.alertname }}
      **Severity:** {{ .Labels.severity }}
      {{ if .Annotations.summary }}**Summary:** {{ .Annotations.summary }}{{ end }}
      {{ if .Annotations.description }}**Description:** {{ .Annotations.description }}{{ end }}
      {{ if .DashboardURL }}**Dashboard:** {{ .DashboardURL }}{{ end }}
      {{ if .SilenceURL }}**Silence:** {{ .SilenceURL }}{{ end }}
      ---
      {{ end }}
