"""Integration tests for presigned URL handling using boto3 signing."""

from typing import Any
from urllib.parse import urlparse

import pytest
from httpx import AsyncClient


@pytest.mark.asyncio
async def test_presigned_get_object_with_access_key(
    boto3_client: Any,
    gateway_client: AsyncClient,
    unique_bucket_name: Any,
) -> None:
    """Presigned GET URL generated by boto3 with hip_ access key should succeed."""
    bucket_name = unique_bucket_name("presigned-get")
    key = "test-object.txt"

    # Generate presigned GET URL via boto3
    presigned_url = boto3_client.generate_presigned_url(
        ClientMethod="get_object",
        Params={"Bucket": bucket_name, "Key": key},
        ExpiresIn=3600,
    )

    parsed = urlparse(presigned_url)

    # Use the in-process gateway_client to exercise only our middleware and S3 API stack
    response = await gateway_client.get(parsed.path + ("?" + parsed.query if parsed.query else ""))

    # Object/bucket may not exist in this in-process gateway, but the important
    # behavior is that the signature is accepted (i.e. we don't return SignatureDoesNotMatch)
    assert response.status_code in (200, 403, 404)
    if response.status_code == 403:
        assert b"SignatureDoesNotMatch" not in response.content


@pytest.mark.asyncio
async def test_presigned_head_object_with_access_key(
    boto3_client: Any,
    gateway_client: AsyncClient,
    unique_bucket_name: Any,
) -> None:
    """Presigned HEAD URL generated by boto3 with hip_ access key should succeed."""
    bucket_name = unique_bucket_name("presigned-head")
    key = "test-object.txt"

    presigned_url = boto3_client.generate_presigned_url(
        ClientMethod="head_object",
        Params={"Bucket": bucket_name, "Key": key},
        ExpiresIn=3600,
    )

    parsed = urlparse(presigned_url)

    response = await gateway_client.head(parsed.path + ("?" + parsed.query if parsed.query else ""))

    assert response.status_code in (200, 403, 404)
    if response.status_code == 403:
        # As above, we only care that the signature is accepted by our middleware
        assert b"SignatureDoesNotMatch" not in response.content
