global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'

  # Redis metrics (main cache)
  - job_name: 'redis-main'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # Redis accounts cache metrics
  - job_name: 'redis-accounts'
    static_configs:
      - targets: ['redis-accounts-exporter:9121']
    scrape_interval: 10s

  # Redis chain cache metrics
  - job_name: 'redis-chain'
    static_configs:
      - targets: ['redis-chain-exporter:9121']
    scrape_interval: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
