apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: local-cache-pv
  resources:
    requests:
      storage: 40Ti
