apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alerts
    receivers:
      - uid: discord-webhook
        type: webhook
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          httpMethod: POST
