apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-alerts
    receivers:
      - uid: discord-webhook
        type: discord
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          message: '{{ template "discord.default.message" . }}'
          title: '{{ template "discord.default.title" . }}'
