apiVersion: 1

policies:
  - orgId: 1
    receiver: discord-alerts
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: discord-alerts
        matchers:
          - severity =~ "critical|high"
        group_wait: 10s
        group_interval: 2m
        repeat_interval: 1h
        continue: false
      - receiver: discord-alerts
        matchers:
          - severity = "medium"
        group_wait: 1m
        group_interval: 5m
        repeat_interval: 4h
        continue: false
