apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-cluster.fullname" . }}-config
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
data:
  redis.conf: |
{{ .Values.configMap.redisConfig | indent 4 }}
