apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}-headless
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    targetPort: redis
    protocol: TCP
  - name: cluster-bus
    port: {{ .Values.redis.clusterBusPort }}
    targetPort: cluster-bus
    protocol: TCP
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: redis
    port: {{ .Values.service.port }}
    targetPort: redis
    protocol: TCP
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
